- name: Main playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: apt update cache (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get update
      register: result

    - name: install python (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get install python3 python3-pip -y
      register: result

    - name: install python modules (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: apt install python3-flask -y
      register: result

    - name: install mysqli extention for php (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: docker-php-ext-install mysqli pdo pdo_mysql
      register: result

    # - name: run vhost2 server
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: nohup python3 /var/www/html/server.py
    #   register: result

    