- name: Main playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: apt update cache (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get update
      register: result

    - name: install python (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get install python3 python3-pip -y
      register: result

    - name: install python modules (vhost2)
      community.docker.docker_container_exec:
        container: vhost2
        command: pip install flask mysql --break-system-packages
      register: result

    # - name: install python modules (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: apt install python3-flask -y
    #   register: result

    # - name: install mysqli extention for php (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: docker-php-ext-install mysqli pdo pdo_mysql
    #   register: result

    # - name: run database creation sql script (database)
    #   community.docker.docker_container_exec:
    #     container: database
    #     command: mysql -u root -proot hospital_db < /var/db/create_db.sql
      
    # - name: run database population sql script (database)
    #   community.docker.docker_container_exec:
    #     container: database
    #     command: mysql -u root -proot hospital_db < /var/db/populate_db.sql

    # - name: execute server.py (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: python3 /var/www/html/server.py
    #   register: result
    
    - name: apt update cache (vhost1)
      community.docker.docker_container_exec:
        container: vhost1
        command: apt-get update
      register: result
      
    
