- name: Main playbook
  hosts: localhost
  gather_facts: true
  tasks:
    # Run backup
    - name: backup data
      community.docker.docker_container_exec:
        container: backup
        command: sh /tmp/backup-script.sh
    
    # Update package lists
    - name: update cache on vhost1
      community.docker.docker_container_exec:
        container: vhost1
        command: apt-get update
    
    - name: update cache on vhost2
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get update

    - name: update cache on vhost3
      community.docker.docker_container_exec:
        container: vhost3
        command: apt-get update

    # Run updates
    - name: update packages on vhost1
      community.docker.docker_container_exec:
        container: vhost1
        command: apt-get upgrade

    - name: update packages on vhost2
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get upgrade

    - name: update packages on vhost3
      community.docker.docker_container_exec:
        container: vhost3
        command: apt-get upgrade

    # Remove unreferenced dependencies
    - name: remove unreferenced dependencies on vhost1
      community.docker.docker_container_exec:
        container: vhost1
        command: apt-get autoremove
    
    - name: remove unreferenced dependencies on vhost2
      community.docker.docker_container_exec:
        container: vhost2
        command: apt-get autoremove

    - name: remove unreferenced dependencies on vhost3
      community.docker.docker_container_exec:
        container: vhost3
        command: apt-get autoremove

    # ## WebServer 1: vhost1
    # - name: apt update cache (vhost1)
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: apt-get update
    #   register: result

    # - name: install python (vhost1)
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: apt-get install python3 python3-pip -y
    #   register: result

    # - name: install flask module for python (vhost1)
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: pip install flask
    #   register: result

    # - name: install mysql module for python (vhost1)
    #   community.docker.docker_container_exec:
    #     container: vhost1
    #     command: pip install pymysql mysql-connector mysql-connector-python
    #   register: result

    # ## WebServer 2: vhost2
    # - name: apt update cache (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: apt-get update
    #   register: result

    # - name: install python (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: apt-get install python3 python3-pip -y
    #   register: result

    # - name: install flask module for python (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: pip install flask --break-system-packages
    #   register: result

    # - name: install mysql module for python (vhost2)
    #   community.docker.docker_container_exec:
    #     container: vhost2
    #     command: pip install pymysql mysql-connector mysql-connector-python --break-system-packages
    #   register: result

    # - name: run database creation sql script (database)
    #   community.docker.docker_container_exec:
    #     container: database
    #     command: mysql -u root -proot hospital_db < /var/db/create_db.sql
    #   register: database_creation
      
    # - name: run database population sql script (database)
    #   community.docker.docker_container_exec:
    #     container: database
    #     command: mysql -u root -proot hospital_db < /var/db/populate_db.sql
    #   when: database_creation.changed

    # - name: execute server.py (vhost2)
    #   community.docker.docker_container_exec:
    #     container: startup
    #     command: docker exec vhost2 "python3 /var/www/html/server.py"
    #   register: result 
    
