version: "3.8"

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - net1
      - net2
      - net3
  
  vhost1:
    container_name: vhost1
    command: sleep infinity
    build:
      context: ./vhost1
      dockerfile: Dockerfile
    volumes:
      - ./vhost1:/var/www/html
      - vhost1_bck:/opt/
    networks:
      - net1
  
  vhost2:
    container_name: vhost2
    command: sleep infinity
    build:
      context: ./vhost2
      dockerfile: Dockerfile
    volumes:
      - ./vhost2/web:/var/www/html
      - vhost2_bck:/opt
    networks:
      - net2
  
  vhost3:
    container_name: vhost3
    command: sleep infinity
    build:
      context: ./vhost3
      dockerfile: Dockerfile
    volumes:
      - vhost3_bck:/opt/
    networks:
      - net3
      
  database:
    image: mysql:latest
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes: 
      - db_data:/var/lib/mysql
      - ./database/scripts:/var/db/
      - database_bck:/opt/
    networks:
      - net1
      - net2
  
  startup:
    container_name: startup
    command: ansible-playbook /opt/playbook.yml
    build:
      context: ./startup
      dockerfile: Dockerfile
    volumes:
      - ./startup:/opt
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vhost1
      - vhost2
      - database
      - proxy
    networks:
      - net1
      - net2
      - net3

  backup:
    container_name: backup
    command: sleep infinity
    build:
      context: ./backup
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vhost1_bck:/opt/vhost1/
      - vhost2_bck:/opt/vhost2/
      - vhost3_bck:/opt/vhost3/
      - database_bck:/opt/database/
      - ./backup/bck:/backup
    depends_on:
      - vhost1
      - vhost2
      - vhost3
      - database

volumes:
  db_data:
  vhost1_bck:
  vhost2_bck:
  vhost3_bck:
  database_bck:

networks:
  net1:
  net2:
  net3: