version: "3.8"

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    networks:
      - net1
      - net2
  
  vhost1:
    container_name: vhost1
    command: sleep infinity
    build:
      context: ./vhost1
      dockerfile: Dockerfile
    volumes:
      - ./vhost1:/var/www/html
    networks:
      - net1
  
  vhost2:
    container_name: vhost2
    command: sleep infinity
    build:
      context: ./vhost2
      dockerfile: Dockerfile
    networks:
      - net2
  
  vhost3:
    container_name: vhost3
    command: sleep infinity
    build:
      context: ./vhost3
      dockerfile: Dockerfile
    networks:
      - net2
  
  vhost4:
    container_name: vhost4
    command: sleep infinity
    build:
      context: ./vhost4
      dockerfile: Dockerfile
    networks:
      - net2
      
  database:
    container_name: database
    command: sleep infinity
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - net3
  
  startup:
    container_name: startup
    command: ansible-playbook /opt/playbook.yml
    build:
      context: ./startup
      dockerfile: Dockerfile
    volumes:
      - ./startup:/opt
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vhost1
      - vhost2
      - database
      - proxy
    networks:
      - net3


networks:
  net1:
  net2:
  net3: