FROM debian:latest

# # Update package list
# RUN apt-get update

# # Download python
# RUN apt-get install python3 python3-pip -y

# # Download Flask library for python
# RUN pip install flask --break-system-packages

# # Download mysql libraries for python
# RUN pip install pymysql mysql-connector mysql-connector-python --break-system-packages

# ENTRYPOINT [ "python3", "/var/www/html/server.py" ]